"""Minimal type stubs for the jq C extension."""

class _ProgramWithInput:
    def all(self) -> list[object]: ...
    def first(self) -> object: ...
    def text(self) -> str: ...

class _Program:
    def input_value(self, value: object) -> _ProgramWithInput: ...
    def input_values(self, *values: object) -> _ProgramWithInput: ...
    def input_text(self, text: str) -> _ProgramWithInput: ...

def compile(program: str) -> _Program: ...
