"""baseline schema

Revision ID: fb4bbf5a1331
Revises:
Create Date: 2026-05-27 08:50:01.823740+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "fb4bbf5a1331"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
    )
    op.create_table(
        "index_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("embedding_provider", sa.String(), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("fingerprint_set_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_index_state_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_state")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("compacted_from_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["compacted_from_id"],
            ["conversations.id"],
            name=op.f("fk_conversations_compacted_from_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_user_id_updated_at"),
            ["user_id", "updated_at"],
            unique=False,
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=True),
        sa.Column("owner_group_id", sa.String(), nullable=True),
        sa.Column("stem_path", sa.String(), nullable=False),
        sa.Column("original_ext", sa.String(), nullable=True),
        sa.Column("has_assets", sa.Boolean(), nullable=False),
        sa.Column(
            "entry_kind",
            sa.Enum(
                "USER_MARKDOWN",
                "IMAGE",
                "CONVERTIBLE",
                "BINARY_STUB",
                name="entrykind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "UPLOAD", "COLLECTION", "EXTRACTED", name="origin", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "generated_by",
            sa.Enum(
                "USER",
                "CONVERTER",
                "VISION",
                "STUB",
                name="generatedby",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("mime", sa.String(), nullable=True),
        sa.Column("pipeline", sa.String(), nullable=False),
        sa.Column("content_sha256", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (owner_group_id IS NOT NULL)",
            name=op.f("ck_documents_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_group_id"],
            ["groups.id"],
            name=op.f("fk_documents_owner_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_documents_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "owner_group_id",
            "stem_path",
            name=op.f("uq_documents_owner_group_id_stem_path"),
        ),
        sa.UniqueConstraint(
            "owner_user_id",
            "stem_path",
            name=op.f("uq_documents_owner_user_id_stem_path"),
        ),
    )
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum("READ", "WRITE", name="permission", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_group_members_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_group_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_group_members")),
    )
    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_members_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "memory",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memory_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_memory")),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
    )
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "chunks",
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("start_index", sa.Integer(), nullable=False),
        sa.Column("end_index", sa.Integer(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id", "idx", name=op.f("pk_chunks")),
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("REQUEST", "RESPONSE", name="messagekind", native_enum=False),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("conversation_id", "idx", name=op.f("pk_messages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("chunks")
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_user_id"))

    op.drop_table("tokens")
    op.drop_table("memory")
    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_members_user_id"))

    op.drop_table("group_members")
    op.drop_table("documents")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_id_updated_at"))

    op.drop_table("conversations")
    op.drop_table("users")
    op.drop_table("index_state")
    op.drop_table("groups")
    # ### end Alembic commands ###
