import type { LucideIcon } from "lucide-react";
import {
  PromptInputSelect,
  PromptInputSelectContent,
  PromptInputSelectItem,
  PromptInputSelectTrigger,
  PromptInputSelectValue,
} from "@/components/ai-elements/prompt-input";

// `PromptInput`'s handleSubmit resets its <form> after capturing the message,
// and a Radix select associated with that form restores its mount-time value on
// reset. Pointing at a form id that must never exist detaches the select from
// that reset. The reset itself cannot be dropped upstream: ai-elements is
// regenerated by the shadcn CLI. Wrapping the composer in `PromptInputProvider`
// would skip it, at the cost of moving the input state out of `ChatSidebar`.
const NONEXISTENT_FORM_ID = "__composer-select-no-form__";

interface ComposerSelectProps<T extends string> {
  value: T;
  onChange: (value: T) => void;
  icon: LucideIcon;
  options: readonly { value: T; label: string; icon?: LucideIcon }[];
}

export function ComposerSelect<T extends string>({
  value,
  onChange,
  icon: Icon,
  options,
}: ComposerSelectProps<T>) {
  return (
    <PromptInputSelect
      form={NONEXISTENT_FORM_ID}
      value={value}
      onValueChange={(v) => onChange(v as T)}
    >
      <PromptInputSelectTrigger className="h-8 w-auto min-w-20">
        <Icon className="h-4 w-4" />
        <PromptInputSelectValue />
      </PromptInputSelectTrigger>
      <PromptInputSelectContent>
        {options.map(({ value: option, label, icon: OptionIcon }) => (
          <PromptInputSelectItem key={option} value={option}>
            {OptionIcon && <OptionIcon className="h-4 w-4" />}
            {label}
          </PromptInputSelectItem>
        ))}
      </PromptInputSelectContent>
    </PromptInputSelect>
  );
}
